Added assignment_2
KanashinDmitry/python_basic_programming pull request #1
Opened 2020-03-15 22:53 UTC by KanashinDmitry

@SpirinEgor, вторая домашка к проверке готова

2020-03-17 14:37 UTC, SpirinEgor requested changes
в .gitignore написано, что бд не надо индексировать (и это правильно), но тем не менее, она почему-то есть в пр.

2020-03-17 14:37 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +                if (key == 'team_name'){
в js
```
3 == '3'
```
возвращает `true`, поэтому лучше использовать `===`

2020-03-17 14:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +               , points text not null)"""
интересный стиль, обычно запятые всё-таки на предыдущей строке пишут

2020-03-17 14:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
>  from flask import Flask, g, request
`request` не используется

2020-04-17 19:10 UTC, KanashinDmitry commented on assignment_2/client/data_worker.js
> +                if (key == 'team_name'){
Исправил

2020-04-17 19:10 UTC, KanashinDmitry commented on assignment_2/server/app_db.py
>  from flask import Flask, g, request
Убрал

2020-04-17 19:13 UTC, KanashinDmitry commented on assignment_2/server/app_db.py
> +               , points text not null)"""
Это удобно, когда много перечислений, чтобы не запутаться, что к чему относиться

2020-04-20 09:52 UTC, SpirinEgor approved these changes

2020-04-21 12:08 UTC, merged